# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.srcs/sources_1/bd/AES128_System/ip/AES128_System_processing_system7_0_0/AES128_System_processing_system7_0_0.xci
# IP: The module: 'AES128_System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.gen/sources_1/bd/AES128_System/ip/AES128_System_processing_system7_0_0/AES128_System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES128_System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.srcs/sources_1/bd/AES128_System/ip/AES128_System_processing_system7_0_0/AES128_System_processing_system7_0_0.xci
# IP: The module: 'AES128_System_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.gen/sources_1/bd/AES128_System/ip/AES128_System_processing_system7_0_0/AES128_System_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'AES128_System_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
