set_property SRC_FILE_INFO {cfile:D:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.srcs/constrs_1/new/zybo_constraints.xdc rfile:../../../project_1.srcs/constrs_1/new/zybo_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports diff_clock_rtl_clk_p]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K16 [get_ports diff_clock_rtl_clk_n]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports reset_rtl]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A9 [get_ports uart_rtl_txd]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B9 [get_ports uart_rtl_rxd]
