set(USER_LINKER_SCRIPT "${CMAKE_CURRENT_SOURCE_DIR}/lscript.ld")

set(USER_COMPILE_SOURCES "")
set(USER_LINK_LIBRARIES "")
set(USER_COMPILE_OPTIONS "")
set(USER_LINK_OPTIONS "")
set(USER_COMPILE_DEFINITIONS "")
set(USER_INCLUDE_DIRECTORIES "")
set(USER_LINK_DIRECTORIES "")