# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_constraints.xdc

# Block Designs: bd/AES128_System/AES128_System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System || ORIG_REF_NAME==AES128_System} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_microblaze_riscv_0_0/AES128_System_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_microblaze_riscv_0_0 || ORIG_REF_NAME==AES128_System_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_dlmb_v10_0/AES128_System_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_dlmb_v10_0 || ORIG_REF_NAME==AES128_System_dlmb_v10_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_ilmb_v10_0/AES128_System_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_ilmb_v10_0 || ORIG_REF_NAME==AES128_System_ilmb_v10_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_dlmb_bram_if_cntlr_0/AES128_System_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==AES128_System_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_ilmb_bram_if_cntlr_0/AES128_System_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==AES128_System_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_lmb_bram_0/AES128_System_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_lmb_bram_0 || ORIG_REF_NAME==AES128_System_lmb_bram_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_microblaze_riscv_0_axi_periph_0/AES128_System_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==AES128_System_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_microblaze_riscv_0_axi_intc_0/AES128_System_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==AES128_System_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_mdm_1_0/AES128_System_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_mdm_1_0 || ORIG_REF_NAME==AES128_System_mdm_1_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_clk_wiz_1_0/AES128_System_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_clk_wiz_1_0 || ORIG_REF_NAME==AES128_System_clk_wiz_1_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_rst_clk_wiz_1_100M_0/AES128_System_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==AES128_System_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_axi_uartlite_0_0/AES128_System_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_axi_uartlite_0_0 || ORIG_REF_NAME==AES128_System_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/AES128_System/ip/AES128_System_processing_system7_0_0/AES128_System_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==AES128_System_processing_system7_0_0 || ORIG_REF_NAME==AES128_System_processing_system7_0_0} -quiet] -quiet

# XDC: d:/AES128-MicroBlaze-V-FPGA/04_Vivado_Project/project_1/project_1.gen/sources_1/bd/AES128_System/AES128_System_ooc.xdc
